site_name: Knowledge Engine
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        # Palette for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
          primary: purple
          accent: amber

        # Palette for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
          primary: purple
          accent: amber

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/kyleanthonyr
        - icon: fontawesome/brands/linkedin
          link: https://linkedin/com/in/kyle-a-rodriguez
